export const LOADING_PURCHASE_DATA = 'LOADING_PURCHASE_DATA';  
export const RECEIVED_PURCHASE_DATA = 'RECEIVED_PURCHASE_DATA';  
export const FETCH_PURCHASE_DATA_FAILED = 'FETCH_PURCHASE_DATA_FAILED';  